"""
Configuration file for D&D World Generator Streamlit App
Customize the application settings here
"""

# Flask Backend Configuration
FLASK_HOST = "localhost"
FLASK_PORT = 5000
FLASK_URL = f"http://{FLASK_HOST}:{FLASK_PORT}"

# Streamlit Configuration
STREAMLIT_PORT = 8501
STREAMLIT_HOST = "localhost"

# Application Settings
APP_TITLE = "🐉 D&D World Generator"
APP_ICON = "🐉"
LAYOUT = "wide"

# Theme Configuration
DARK_THEME = True
PRIMARY_COLOR = "#4dabf7"
BACKGROUND_COLOR = "#0f1419"
SECONDARY_BACKGROUND = "#1a1a2e"
TEXT_COLOR = "#e6edf3"

# Combat Grid Settings
DEFAULT_GRID_SIZE = 20
GRID_LINE_COLOR = "#2d3742"
COMBATANT_MARKER_SIZE = 25

# Dice Roller Settings
DEFAULT_DICE = "1d20"
SHOW_INDIVIDUAL_ROLLS = True
SHOW_MODIFIERS = True
ENABLE_ADVANTAGE_DISADVANTAGE = True

# Character Creation Settings
DEFAULT_ABILITY_SCORE_METHOD = "4d6"
RACIAL_BONUSES_ENABLED = True
AUTO_CALCULATE_MODIFIERS = True

# Spell System Settings
SHOW_SPELL_SLOTS_VISUAL = True
ENABLE_CANTRIP_CASTING = True
AUTO_DEDUCT_SPELL_SLOTS = True

# Story Generator Settings
DEFAULT_STORY_LENGTH = "medium"
ENABLE_CHARACTER_CONTEXT = True
DEFAULT_ENVIRONMENT = "any"

# Performance Configuration
ENABLE_CACHING = True
CACHE_TTL_SHORT = 10
CACHE_TTL_MEDIUM = 30
CACHE_TTL_LONG = 300

ENABLE_HEALTH_CHARTS = True
ENABLE_SPATIAL_COMBAT_VISUAL = False
CHART_ANIMATION = False
CHART_HEIGHT = 400

# API Timeout Settings
API_TIMEOUT_SHORT = 2
API_TIMEOUT_MEDIUM = 3
API_TIMEOUT_LONG = 8

# UI Performance Settings
AUTO_REFRESH_INTERVAL = 30
SHOW_LOADING_SPINNERS = True
LAZY_LOAD_CHARTS = True
MINIMIZE_REDRAWS = True

# Cache Settings
CACHE_CHARACTER_DATA = True
CACHE_DURATION = 300

# Feature Flags
ENABLE_SPATIAL_COMBAT = True
ENABLE_STORY_GENERATOR = True
ENABLE_ADVANCED_DICE = True
ENABLE_SPELL_MANAGEMENT = True
ENABLE_INVENTORY_INTEGRATION = True

# Notification Settings
SHOW_CRITICAL_ROLL_NOTIFICATIONS = True
SHOW_COMBAT_NOTIFICATIONS = True
SHOW_SPELL_CAST_NOTIFICATIONS = True

# Data Validation
VALIDATE_CHARACTER_DATA = True
VALIDATE_DICE_NOTATION = True
VALIDATE_SPELL_SLOTS = True

# Export/Import Settings
ENABLE_CHARACTER_EXPORT = True
ENABLE_CAMPAIGN_BACKUP = True
EXPORT_FORMAT = "json"

# Advanced Features
ENABLE_ANALYTICS = False
ENABLE_MULTIPLAYER = False
ENABLE_VOICE_COMMANDS = False

# Error Handling
MAX_RETRIES = 3
RETRY_DELAY = 1
GRACEFUL_DEGRADATION = True